version: '3'

services:
  frontend:
    container_name: web-server
    build: ./frontend
    ports:
      - 4200:4200
  backend:
    container_name: app-server
    build: ./backend
    ports:
      - 8080:8080